#+TITLE: Who4mos`s Emacs Configuration
#+AUTHOR: who4mos
#+STARTUP: overview
#+PROPERTY: header-args :tangle ~/.config/emacs/init.el

* TOC :TOC:
- [[#packages][Packages]]
  - [[#packageel][Package.el]]
  - [[#use-package][use-package]]
  - [[#try][try]]
- [[#ui][UI]]
  - [[#remove-welcome-screen][Remove Welcome Screen]]
  - [[#cleaning-interface][Cleaning Interface]]
  - [[#theme][Theme]]
  - [[#font][Font]]
  - [[#line-numbers][Line Numbers]]
  - [[#helpful][helpful]]
  - [[#dired][dired]]
- [[#key-bindings][Key Bindings]]
  - [[#revert-buffer][revert buffer]]
  - [[#which-key][which-key]]
- [[#navigation][Navigation]]
  - [[#ace-window][ace-window]]
  - [[#avy][avy]]
  - [[#multiple-cursors][multiple-cursors]]
  - [[#expand-region][expand-region]]
- [[#minibuffer][Minibuffer]]
  - [[#vertico][vertico]]
  - [[#consult][consult]]
- [[#mode-line][Mode-line]]
  - [[#nyan-mode][nyan-mode]]
  - [[#minions][minions]]
- [[#fuzzy][Fuzzy]]
  - [[#orderless][Orderless]]
- [[#programming][Programming]]
  - [[#magit][Magit]]
  - [[#eglot][Eglot]]
  - [[#corfu][corfu]]
  - [[#flycheck][flycheck]]
  - [[#yasnippet][yasnippet]]
  - [[#smartparens][smartparens]]
  - [[#rainbow-delimiters][rainbow-delimiters]]
  - [[#lua-mode][lua-mode]]
- [[#org-mode][Org-mode]]
  - [[#scratch-org-buffer][Scratch Org Buffer]]
  - [[#capture][Capture]]
  - [[#beautifying-org][Beautifying Org]]
  - [[#org-modern][org-modern]]
  - [[#org-appear][org-appear]]
  - [[#org-tempo][org-tempo]]
  - [[#toc-org][toc-org]]
- [[#pdf-tools][PDF Tools]]
  - [[#pdf-view-restore][pdf-view-restore]]
- [[#vterm][vterm]]
  - [[#vterm-toggle][vterm-toggle]]
- [[#misc][MISC]]
  - [[#accent][accent]]

* Packages

** Package.el

#+begin_src emacs-lisp
  (require 'package)
  (setq package-enable-at-startup nil)
  (unless (assoc-default "melpa" package-archives)
    (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t))
  (package-initialize)
#+end_src

** use-package

[[https://github.com/jwiegley/use-package][use-package]] is used to configure and load packages.

#+begin_src emacs-lisp
  (unless (package-installed-p 'use-package)
    (package-install 'use-package))
  (setq use-package-always-ensure t)
  (require 'use-package)
#+end_src

** try

[[https://github.com/larstvei/Try][try]] is a package to try emacs packages.

#+begin_src emacs-lisp
  (use-package try)
#+end_src

* UI

** Remove Welcome Screen

#+begin_src emacs-lisp
  (setq inhibit-startup-message t)
#+end_src

** Cleaning Interface

#+begin_src emacs-lisp
  (menu-bar-mode -1)
  (tool-bar-mode -1)
  (scroll-bar-mode -1)
#+end_src

** Theme

#+begin_src emacs-lisp
  (use-package ef-themes
    :config
    (load-theme 'ef-winter t))
#+end_src

** Font

#+begin_src emacs-lisp
  (set-face-attribute 'default nil :font "Iosevka Extended" :height 120)
#+end_src

*** nerd-icons

[[https://github.com/rainstormstudio/nerd-icons.el][nerd-icons]] is a library to use nerd fonts in emacs.

#+begin_src emacs-lisp
  (use-package nerd-icons
    :custom
    (nerd-icons-font-family "Iosevka Nerd Font"))
 #+end_src

** Line Numbers

#+begin_src emacs-lisp
  (add-hook 'prog-mode-hook 'display-line-numbers-mode)
#+end_src

** helpful

[[https://github.com/Wilfred/helpful][helpful]] provides more information to emacs built-in help buffers.

#+begin_src emacs-lisp
  (use-package helpful
    :bind
    ([remap describe-function] . helpful-callable)
    ([remap describe-variable] . helpful-variable)
    ([remap describe-key] . helpful-key)
    ([remap describe-command] . helpful-command)
    )
#+end_src

** dired

Change arguments passed to ~ls~.

#+begin_src emacs-lisp
  (setq dired-listing-switches "-agho --group-directories-first")
#+end_src

*** nerd-icons-dired

[[https://github.com/rainstormstudio/nerd-icons-dired][nerd-icons-dired]] allows you to use nerd-icons with dired.

#+begin_src emacs-lisp
  (use-package nerd-icons-dired
    :hook
    (dired-mode . nerd-icons-dired-mode))
#+end_src

* Key Bindings

** revert buffer

#+begin_src emacs-lisp
  (global-set-key (kbd "<f5>") 'revert-buffer)
#+end_src

** which-key

[[https://github.com/justbur/emacs-which-key][which-key]] is a package that displays the key bindings following the entered input so far.

#+begin_src emacs-lisp
      (use-package which-key
	:config
	(which-key-mode))
#+end_src

* Navigation

** ace-window

[[https://github.com/abo-abo/ace-window][ace-window]] is a package that provides a better way to select windows.

#+begin_src emacs-lisp
  (global-unset-key (kbd "C-x o"))

  (use-package ace-window
    :bind
    ("M-o" . ace-window))
#+end_src

** avy

[[https://github.com/abo-abo/avy][avy]] is a package that allows you to jump to text choosing between characters.

#+begin_src emacs-lisp
  (use-package avy
    :bind
    ("M-s" . avy-goto-char))
#+end_src

** multiple-cursors

[[https://github.com/magnars/multiple-cursors.el][multiple-cursors]] provides multiple cursors.

#+begin_src emacs-lisp
  (use-package multiple-cursors
    :bind
    ("C-S-c C-S-c" . mc/edit-lines)
    ("C-S-c C-e" . mc/edit-ends-of-lines)
    ("C-S-c C-a" . mc/edit-beginnings-of-lines)
    ("C->" . mc/mark-next-like-this)
    ("C-<" . mc/mark-previous-like-this))
#+end_src

** expand-region

[[https://github.com/magnars/expand-region.el][expand-region]] is a package that allows you to increases the selected region by semantic units.

#+begin_src emacs-lisp
  (use-package expand-region
    :bind ("C-=" . er/expand-region))
#+end_src

* Minibuffer

** vertico

[[https://github.com/minad/vertico][vertico]] (VERTIcal Interactive COmpletion) provides a completion UI based on the bult-in completion system.

#+begin_src emacs-lisp
  (use-package vertico
    :custom
    (vertico-cycle t)
    :init
    (vertico-mode))
#+end_src

*** marginalia

[[https://github.com/minad/marginalia][marginalia]] is a package that provides marks and annotations to minibuffer candidates.

#+begin_src emacs-lisp
  (use-package marginalia
    :init
    (marginalia-mode))
#+end_src

**** nerd-icons-completion

[[https://github.com/rainstormstudio/nerd-icons-completion][nerd-icons-completion]] use nerd icons to add icons with marginalia.

#+begin_src emacs-lisp
  (use-package nerd-icons-completion
    :after marginalia
    :config
    (nerd-icons-completion-mode)
    (add-hook 'marginalia-mode-hook #'nerd-icons-completion-marginalia-setup))
#+end_src

** consult

[[https://github.com/minad/consult][consult]] provides search and navigation commands based in the built-in complete system.

#+begin_src emacs-lisp
  (use-package consult
    :bind
    ([remap isearch-forward] . consult-line)
    ([remap imenu] . consult-imenu)
    ([remap goto-line] . consult-goto-line)
    ("C-c M-x" . consult-mode-command)
    ("C-c i" . consult-info)
    ("C-x b" . consult-buffer)
    ("M-y" . consult-yank-pop)
    :config
    (add-hook 'org-mode-hook
	      (lambda ()
		(local-set-key (kbd "M-g i") #'consult-org-heading))))
#+end_src

* Mode-line 

** nyan-mode

[[https://github.com/TeMPOraL/nyan-mode][nyan-mode]] indicates your position in a buffer...

#+begin_src emacs-lisp
  (use-package nyan-mode
    :custom
    (nyan-animate-nyancat t)
    (nyan-wavy-trail t)
    :config
    (nyan-mode))
#+end_src

** minions

[[https://github.com/tarsius/minions][minions]] nests all minor modes into a single one.

#+begin_src emacs-lisp
  (use-package minions
    :init
    (minions-mode))
#+end_src

* Fuzzy

** Orderless

[[https://github.com/oantolin/orderless][orderless]] is package that provides a completion style that divides the pattern into space-separated components.

#+begin_src emacs-lisp
  (use-package orderless
    :custom
    (completion-styles '(orderless basic))
    (completion-category-defaults nil)
    (completion-category-overrides '((file (styles basic partial-completion)))))
#+end_src

* Programming

** Magit

[[https://github.com/magit/magit][Magit]] is a git porcelain inside emacs.

#+begin_src emacs-lisp
  (use-package magit)
#+end_src

*** git-timemachine

[[https://github.com/emacsmirror/git-timemachine][git-timemachine]] allows you to go back and forth in time in a git directory.

#+begin_src emacs-lisp
  (use-package git-timemachine)
#+end_src

** Eglot

[[https://github.com/joaotavora/eglot][Eglot]] is the emacs built-in [[https://en.wikipedia.org/wiki/Language_Server_Protocol][LSP]] client.

#+begin_src emacs-lisp
  (with-eval-after-load 'eglot
  (add-to-list 'eglot-server-programs
	       '(python-mode . ("pyright-langserver" "--stdio"))))

  (add-hook 'python-mode-hook 'eglot-ensure)
  (add-hook 'c-mode-hook 'eglot-ensure)
  (add-hook 'js-mode-hook 'eglot-ensure)
#+end_src

** corfu

[[https://github.com/minad/corfu][corfu]] enhances completion with a small completion popup.

#+begin_src emacs-lisp
  (use-package corfu
    :custom
    (corfu-cycle t)
    (corfu-auto t)
    (corfu-auto-prefix 2)
    (corfu-popupinfo-delay '(0.5 . 0.0))
    :init
    (global-corfu-mode)
    (corfu-popupinfo-mode))
#+end_src

*** nerd-icons-corfu

[[https://github.com/LuigiPiucco/nerd-icons-corfu][nerd-icons-corfu]] uses nerd icons to add icons in corfu completions.

#+begin_src emacs-lisp
  (use-package nerd-icons-corfu
    :init
    (add-to-list 'corfu-margin-formatters #'nerd-icons-corfu-formatter))
#+end_src

*** cape

[[https://github.com/minad/cape][cape]] provides completion extensions that can be used with corfu.

#+begin_src emacs-lisp
  (use-package cape
    :init
    (add-to-list 'completion-at-point-functions #'cape-file)
    (add-to-list 'completion-at-point-functions #'cape-elisp-block))
#+end_src

** flycheck

[[https://github.com/flycheck/flycheck][flycheck]] is a modern systax check extension for Emacs.

#+begin_src emacs-lisp
  (use-package flycheck
    :init
    (global-flycheck-mode))
#+end_src

** yasnippet

[[https://github.com/joaotavora/yasnippet][yasnippet]] is a template system for Emacs.

#+begin_src emacs-lisp
  (use-package yasnippet
    :config
    (yas-global-mode))
#+end_src

*** yasnippet-snippets

[[https://github.com/AndreaCrotti/yasnippet-snippets][yasnippet-snippets]] contains a collection of snippets for yasnippet.

#+begin_src emacs-lisp
  (use-package yasnippet-snippets)
#+end_src

** smartparens

[[https://github.com/Fuco1/smartparens][smartparens]] is a minor mode for dealing with pairs.

#+begin_src emacs-lisp
  (use-package smartparens
    :hook
    (prog-mode . smartparens-mode)
    :config
    (require 'smartparens-config))
#+end_src

** rainbow-delimiters

[[https://github.com/Fanael/rainbow-delimiters][rainbow-delimiters]] highlights delimiters according to their depths.

#+begin_src emacs-lisp
  (use-package rainbow-delimiters
    :hook
    (prog-mode . rainbow-delimiters-mode))
#+end_src

** lua-mode

[[https://github.com/immerrr/lua-mode][lua-mode]] is a major mode for editing Lua sources.

#+begin_src emacs-lisp
  (use-package lua-mode
    :config
    (autoload 'lua-mode "lua-mode" "Lua editing mode." t)
    (add-to-list 'auto-mode-alist '("\\.lua$" . lua-mode))
    (add-to-list 'interpreter-mode-alist '("lua" . lua-mode)))
#+end_src

* Org-mode

** Scratch Org Buffer

Change scratch-buffer's mode. 

#+begin_src emacs-lisp
  (setq
   initial-major-mode 'org-mode
   initial-scratch-message "")
#+end_src

** Capture

Setup [[https://orgmode.org/manual/Using-capture.html][org-capture]] and define a template to capture bookmarks.

#+begin_src emacs-lisp
  (global-set-key (kbd "C-c c") 'org-capture)

  (setq org-capture-templates
      '(("b" "Bookmark"
	 entry (file+headline "~/bookmarks.org" "Bookmarks")
	 "* [[%^{Link}][%^{Description}]]")))
#+end_src

** Beautifying Org

#+begin_src emacs-lisp
  (add-hook 'org-mode-hook 'visual-line-mode)

  (custom-set-faces
   '(org-level-1 ((t (:height 1.2))))
   '(org-level-2 ((t (:height 1.0))))
   '(org-level-3 ((t (:height 0.9))))
   '(org-level-4 ((t (:height 0.9))))
   '(org-level-5 ((t (:height 0.9))))
   '(org-level-6 ((t (:height 0.9))))
   '(org-level-7 ((t (:height 0.9))))
   '(org-level-8 ((t (:height 0.9))))
   '(org-level-9 ((t (:height 0.9))))
   )

  (setq
   org-auto-align-tags nil
   org-tags-column 0
   org-special-ctrl-a/e t
   org-ellipsis " ▾"
   org-hide-emphasis-markers t
   org-agenda-tags-column 0
   
   )
#+end_src

** org-modern

[[https://github.com/minad/org-modern][org-modern]] provides a modern look to org-mode.

#+begin_src emacs-lisp
  (use-package org-modern
    :hook
    (org-mode . org-modern-mode)
    (org-agenda-finalize . org-modern-agenda))
#+end_src

** org-appear

[[https://github.com/awth13/org-appear][org-appear]] automatically toggles visibility of hidden elements like emphasis markers.

#+begin_src emacs-lisp
  (use-package org-appear
    :hook
    (org-mode . org-appear-mode))
#+end_src

** org-tempo

#+begin_src emacs-lisp
  (with-eval-after-load 'org
    (add-to-list 'org-modules 'org-tempo))
  #+end_src

** toc-org

#+begin_src emacs-lisp
  (use-package toc-org
    :hook
    (org-mode . toc-org-mode))
#+end_src

* PDF Tools

#+begin_src emacs-lisp
  (use-package pdf-tools)
#+end_src

** pdf-view-restore

[[https://github.com/007kevin/pdf-view-restore][pdf-view-restore]] remember pdf position in pdf-view-mode.

#+begin_src emacs-lisp
  (use-package pdf-view-restore
    :after pdf-tools
    :hook
    (pdf-view-mode . pdf-view-restore-mode)
    :custom
    (pdf-view-restore-filename (expand-file-name ".pdf-view-restore" user-emacs-directory)))
#+end_src

* vterm

#+begin_src emacs-lisp
  (use-package vterm)
#+end_src

** vterm-toggle

#+begin_src emacs-lisp
  (use-package multi-vterm
    :bind
    ("C-\"" . multi-vterm-dedicated-toggle)
    :custom
    ( multi-vterm-dedicated-window-height-percent 30))
#+end_src

* MISC

** accent

[[https://github.com/eliascotto/accent][accent]] opens a menu with accented chars.

#+begin_src emacs-lisp
  (use-package accent
    :bind
    ("C-x C-a" . accent-menu))
#+end_src
