#+TITLE: Emacs Configuration  
#+AUTHOR: who4mos
#+PROPERTY: header-args :tangle ~/.config/emacs/init.el
#+auto_tangle: t

* Packages
Package initialization.

#+BEGIN_SRC emacs-lisp
  (require 'package)

  (setq package-archives '(("melpa" . "https://melpa.org/packages/")
                           ("gnu" . "https://elpa.gnu.org/packages/")
                           ("nongnu" . "https://elpa.nongnu.org/nongnu/")))

  (package-initialize)
#+END_SRC

** USE-PACKAGE

#+BEGIN_SRC emacs-lisp
  (unless (package-installed-p 'use-package)
    (package-refresh-contents)
    (package-install 'use-package))

  (require 'use-package)
  (setq use-package-always-ensure t)
#+END_SRC

** TRY

#+BEGIN_SRC emacs-lisp
  (use-package try)
#+END_SRC

* GENERAL
** CLEANING INIT FILE
Move custom vars to another file.

#+BEGIN_SRC emacs-lisp
  (setq custom-file (locate-user-emacs-file "custom-vars.el"))
  (load custom-file)
#+END_SRC

** UI
Disable wellcome screen, scroll, tool, and menu bars, and shows lines on almost all buffers.

#+BEGIN_SRC emacs-lisp
  (setq inhibit-startup-message t)

  (scroll-bar-mode -1)
  (tool-bar-mode -1)
  (menu-bar-mode -1)

  (global-display-line-numbers-mode 1)
  (dolist (mode '(org-mode-hook
                  term-mode-hook
                  shell-mode-hook
                  eshell-mode-hook))
    (add-hook mode (lambda () (display-line-numbers-mode -1))))
#+END_SRC

*** FONT
Font configuration.

#+BEGIN_SRC emacs-lisp
  (set-face-attribute 'default nil :family "JetBrains Mono")
#+END_SRC

*** LIGATURES
Enable font ligatures.

#+BEGIN_SRC emacs-lisp
      (use-package ligature
        :config
        ;; Enable all JetBrains Mono ligatures in programming modes
        (ligature-set-ligatures 'html-mode '("<!--" "-->" "</>" "</" "/>" "://"))
        (ligature-set-ligatures 'prog-mode '("-|" "-~" "---" "-<<" "-<" "--" "->" "->>" "-->" "///" "/=" "/=="
                                             "/>" "//" "/*" "*>" "***" "*/" "<-" "<<-" "<=>" "<=" "<|" "<||"
                                             "<|||" "<|>" "<:" "<>" "<-<" "<<<" "<==" "<<=" "<=<" "<==>" "<-|"
                                             "<<" "<~>" "<=|" "<~~" "<~" "<$>" "<$" "<+>" "<+" "</>" "</" "<*"
                                             "<*>" "<->" "<!--" ":>" ":<" ":::" "::" ":?" ":?>" ":=" "::=" "=>>"
                                             "==>" "=/=" "=!=" "=>" "===" "=:=" "==" "!==" "!!" "!=" ">]" ">:"
                                             ">>-" ">>=" ">=>" ">>>" ">-" ">=" "&=" "&&&" "&&" "|||>" "||>" "|>" "|]"
                                             "|}" "|=>" "|->" "|=" "||-" "|-" "||=" "||" ".." ".?" ".=" ".-" "..<"
                                             "..." "+++" "+>" "++" "[||]" "[<" "[|" "{|" "??" "?." "?=" "?:" "##"
                                             "###" "####" "#[" "#{" "#=" "#!" "#:" "#_(" "#_" "#?" "#(" ";;" "_|_"
                                             "__" "~~" "~~>" "~>" "~-" "~@" "$>" "^=" "]#"))
        ;; Enables ligature checks globally in all buffers. You can also do it
        ;; per mode with `ligature-mode'.
        (global-ligature-mode t))
  #+END_SRC

*** THEME
  
#+BEGIN_SRC emacs-lisp
    (use-package doom-themes
      :config (load-theme 'doom-dracula t))
#+END_SRC

*** ALL THE ICONS
You must run ~M-x all-the-icons-install-fonts~ after install the package.
- [[https://github.com/domtronn/all-the-icons.el][Github]]

#+BEGIN_SRC emacs-lisp
  (use-package all-the-icons
    :if (display-graphic-p))
#+END_SRC

** MODE LINE
*** DOOM-MODELINE

#+BEGIN_SRC emacs-lisp
  (use-package doom-modeline
    :custom
    (doom-modeline-minor-modes t)
    :init (doom-modeline-mode 1))
#+END_SRC

*** MINIONS
#+BEGIN_SRC emacs-lisp
    (use-package minions
      :config (minions-mode))
#+END_SRC

** MINIBUFFER
*** VERTICO
VERTICO (VERTical Interative COmpletion) provides a minimalist vertical completion UI based on the default completion system.

- [[https://github.com/minad/vertico][Github]]
  
#+BEGIN_SRC emacs-lisp
  (use-package vertico
    :custom
    (vertico-cycle t)
    :config
    (vertico-mode))
#+END_SRC

*** MARGINALIA
Show documentation of functions in ~M-x~ and file attributes in ~C-x C-f~. 

- [[https://github.com/minad/marginalia]]
    
#+BEGIN_SRC emacs-lisp
  (use-package marginalia
    :after vertico
    :init
    (marginalia-mode 1))
#+END_SRC

*** CONSULT
Provides search and navigation commands based on the default completion system.

- [[https://github.com/minad/consult]]
  
#+BEGIN_SRC emacs-lisp
  (use-package consult
    :bind
    ("M-y" . consult-yank-pop)
    ("C-s" . consult-line))
#+END_SRC

*** ORDERLESS
- [[https://github.com/oantolin/orderless][Github]]

#+BEGIN_SRC emacs-lisp
  (use-package orderless
    :custom
    (completion-styles '(orderless basic))
    (completion-category-defaults nil)
    (completion-category-overrides '((file (styles . (partial-completion))))))
      #+END_SRC

** HELPERS
*** HELPFUL

#+BEGIN_SRC emacs-lisp
  (use-package helpful
    :bind
    ([remap describe-function] . helpful-callable)
    ([remap describe-variable] . helpful-variable)
    ([remap describe-command] . helpful-command)
    ([remap describe-symbol] . helpful-symbol)
    ([remap describe-key] . helpful-key))
#+END_SRC

*** WHICH KEY

#+BEGIN_SRC emacs-lisp
  (use-package which-key
    :config
    (which-key-mode 1))
#+END_SRC

** AVY

#+BEGIN_SRC emacs-lisp
  (use-package avy
    :bind
    ("M-s" . avy-goto-char)
    ([remap goto-line] . avy-goto-line))
#+END_SRC

** ACE WINDOW

#+BEGIN_SRC emacs-lisp
  (use-package ace-window
    :bind
    ([remap other-window] . ace-window)
    :init
    (custom-set-faces
     '(aw-leading-char-face
       ((t (:inherit ace-jump-face-foreground :height 1.5))))))
#+END_SRC

** EXPAND REGION
- [[https://emacsrocks.com/e09.html][emacs rocks]]
- [[https://github.com/magnars/expand-region.el][github]]

#+BEGIN_SRC emacs-lisp
  (use-package expand-region
    :bind ("C-=" . er/expand-region))
#+END_SRC

* DEVELOPMENT
** RAINBOW DELIMITERS

#+BEGIN_SRC emacs-lisp
  (use-package rainbow-delimiters
    :hook (prog-mode . rainbow-delimiters-mode))
#+END_SRC

** SMARTPARENS

- [[https://github.com/Fuco1/smartparens][Github]]

#+BEGIN_SRC emacs-lisp
        (use-package smartparens
          :config (require 'smartparens-config)
          :hook (prog-mode . smartparens-mode))
#+END_SRC

** FLYCHECK

    #+BEGIN_SRC emacs-lisp
      (use-package flycheck
        :init (global-flycheck-mode))
    #+END_SRC

** CORFU

#+BEGIN_SRC emacs-lisp
    (use-package corfu
      :custom
      (corfu-cycle t)
      (corfu-auto t)
      :bind
      (:map corfu-map
            ("C-f" . corfu-insert))
      :init
      (global-corfu-mode))
#+END_SRC

*** KIND-ICONS

#+BEGIN_SRC emacs-lisp
  (use-package kind-icon
    :after corfu
    :custom
    (kind-icon-default-face 'corfu-default)
    :config
    (add-to-list 'corfu-margin-formatters #'kind-icon-margin-formatter))
#+END_SRC

** EGLOT

#+BEGIN_SRC emacs-lisp
  (use-package eglot)
#+END_SRC

* ORG MODE

#+BEGIN_SRC emacs-lisp
  (use-package org
    :custom
    (org-hide-emphasis-markers t) 
    (org-ellipsis " ▾")
    :hook
    (org-mode . visual-line-mode)
    (org-mode . org-indent-mode))
#+END_SRC

** ORG AUTO TANGLE

#+BEGIN_SRC emacs-lisp
  (use-package org-auto-tangle
    :defer t
    :hook (org-mode . org-auto-tangle-mode))
#+END_SRC

** ORG SUPERSTAR

#+BEGIN_SRC emacs-lisp
  (use-package org-superstar
    :custom
    (org-superstar-leading-bullet " ")
    :config
    (add-hook 'org-mode-hook (lambda () (org-superstar-mode 1))))
#+END_SRC

* KEY BINDINGS

** REVERT-BUFFER

#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "<f5>") 'revert-buffer)
#+END_SRC

