#+TITLE: Emacs Configuration
#+PROPERTY: header-args :tangle ~/.config/emacs/init.el

* Package Management

[[https://github.com/radian-software/straight.el][straight.el]] is a package manager, it substitutes ~package.el~.

With ~straight.el~, you can give a recipe for specific packages and where to find them. Also, packages are cloned as git repos, not tarballs. You have more control over your packages.

First, you need to disable ~package.el~ by adding this line to the [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Early-Init-File.html][early init file]]:

#+begin_src emacs-lisp :tangle ~/.config/emacs/early-init.el
  (setq package-enable-at-startup nil)
#+end_src

Then, add the straight bootstrap code:

#+begin_src emacs-lisp
  (defvar bootstrap-version)
  (let ((bootstrap-file
         (expand-file-name
          "straight/repos/straight.el/bootstrap.el"
          (or (bound-and-true-p straight-base-dir)
              user-emacs-directory)))
        (bootstrap-version 7))
    (unless (file-exists-p bootstrap-file)
      (with-current-buffer
          (url-retrieve-synchronously
           "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
           'silent 'inhibit-cookies)
        (goto-char (point-max))
        (eval-print-last-sexp)))
    (load bootstrap-file nil 'nomessage))
#+end_src

** use-package

[[https://www.emacswiki.org/emacs/UsePackage][use-package]] allows you to configure packages in a isolate and declarative way. ~use-package~ is now a built-in package. Since emacs 29.1, ~use-package~ is a built-in package.

Before using it, tell ~use-package~ to use ~straight.el~.

#+begin_src emacs-lisp
  (setq straight-use-package-by-default t)
#+end_src

* UI

Inhibit startup screen and remove bars to a cleaner UI.

#+begin_src emacs-lisp
  (setq inhibit-startup-screen t)
  (scroll-bar-mode -1)
  (menu-bar-mode -1)
  (tool-bar-mode -1)
#+end_src

** Theme

[[https://protesilaos.com/emacs/ef-themes][ef-themes]]

#+begin_src emacs-lisp
  (use-package ef-themes
    :config
    (load-theme 'ef-dream :no-confirm))
#+end_src

** Font

Set font to [[https://github.com/source-foundry/Hack][Hack]].

#+begin_src emacs-lisp
  (add-to-list 'default-frame-alist
               '(font . "Hack Nerd Font-11"))
#+end_src

** Icons

[[https://github.com/rainstormstudio/nerd-icons.el][nerd-icons]] allows you to use [[https://github.com/ryanoasis/nerd-fonts][nerd-fonts]] inside emacs.

#+begin_src emacs-lisp
  (use-package nerd-icons
    :custom
    (nerd-icons-font-family "Hack Nerd Font"))
#+end_src

** Mode Line

[[https://github.com/seagle0128/doom-modeline?tab=readme-ov-file][doom-modeline]] is a fast and minimal mode-line. It offers a lot of cool features and works well with a lot of other packages.

#+begin_src emacs-lisp
  (use-package doom-modeline
    :custom
    (doom-modeline-height 25)
    :hook
    (after-init . doom-modeline-mode))
#+end_src

** helpful

[[https://github.com/Wilfred/helpful][helpful]] substitutes the built-in help system, it gives a lot of /helpful/ information.

#+begin_src emacs-lisp
  (use-package helpful
    :bind (
           ([remap describe-key]      . helpful-key)
           ([remap describe-function] . helpful-callable)
           ([remap describe-variable] . helpful-variable)
           ([remap describe-command]  . helpful-command)))
#+end_src

* Window Management

[[https://github.com/abo-abo/ace-window][ace-window]] helps you to select a window and switch to it.

#+begin_src emacs-lisp
  (use-package ace-window
    :bind
    ("M-o" . ace-window))
#+end_src

* File Management

Move backup files to a single directory.

#+begin_src emacs-lisp
  (setq backup-directory-alist '(("." . "~/.config/emacs/backups")))
#+end_src

Set ~ls~ parameters to use in [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Dired-Enter.html][dired]].

#+begin_src emacs-lisp
  (setq dired-listing-switches "-lah --group-directories-first")
#+end_src

[[https://github.com/rainstormstudio/nerd-icons-dired][nerd-icons-dired]] allows nerd-icons to be used in dired.

#+begin_src emacs-lisp
  (use-package nerd-icons-dired
    :hook
    (dired-mode . nerd-icons-dired-mode))
#+end_src

** Sidebar

[[https://github.com/jojojames/dired-sidebar][dired-sidebar]] provides a sidebar based on dired.

#+begin_src emacs-lisp
  (use-package dired-sidebar
    :commands (dired-sidebar-toggle-sidebar)
    :bind
    ("C-;" . dired-sidebar-toggle-sidebar))
#+end_src

* Search and Navigation

[[https://github.com/minad/consult][consult]] provides search and navigation commands based on the built-in completion function ~completing-read~.

#+begin_src emacs-lisp
  (use-package consult
    :bind (
           ([remap isearch-forward] . consult-line)
           ([remap go-to-line] . consult-go-to-line)
           ([remap switch-to-buffer] . consult-buffer)
           ([remap yank-pop] . consult-yank-pop)
           ([remap info] . consult-info)
           ([remap imenu] . consult-imenu)
           ("C-c M-x" . consult-mode-command)
           ("C-c m" . consult-man)))
#+end_src

[[https://github.com/abo-abo/avy][avy]] allows you to jump to visible text by selecting a character.

#+begin_src emacs-lisp
  (use-package avy
    :bind
    ("M-s" . avy-goto-char))
#+end_src

* Completion

There are completions in-buffer and in the minibuffer. There are also some tools that allows fuzzy and narrowed searches.

** Minibuffer

[[https://github.com/minad/vertico][vertico]] is a minimalist completion UI based on the built-in completion system.

#+begin_src emacs-lisp
  (use-package vertico
    :custom
    (vertico-cycle t)
    :init
    (vertico-mode))
#+end_src

*** Marginalia

[[https://github.com/minad/marginalia][marginalia]] adds marginalia to minibuffer completions.

#+begin_src emacs-lisp
  (use-package marginalia
    :init
    (marginalia-mode))
#+end_src

*** Icons

#+begin_src emacs-lisp
  (use-package nerd-icons-completion
    :config
    (nerd-icons-completion-mode))
#+end_src

** In Buffer

[[https://github.com/minad/corfu][corfu]] enhances in-buffer completion with popups.

#+begin_src emacs-lisp
  (use-package corfu
    :custom
    (corfu-cycle t)
    (corfu-auto t)
    (corfu-auto-prefix 2)
    (corfu-popupinfo-delay '(1.0 . 0))
    (text-mode-ispell-word-completion nil)
    :init
    (global-corfu-mode)
    (corfu-popupinfo-mode))
#+end_src

*** Icons

#+begin_src emacs-lisp
  (use-package nerd-icons-corfu
     :config
     (add-to-list 'corfu-margin-formatters #'nerd-icons-corfu-formatter))
#+end_src

*** Cape

[[https://github.com/minad/cape][cape]] provides completion extensions.

#+begin_src emacs-lisp
  (use-package cape
      :init
      (add-hook 'completion-at-point-functions #'cape-file)
      (add-hook 'completion-at-point-functions #'cape-elisp-block))
#+end_src

** Completion Style

[[https://github.com/oantolin/orderless][orderless]] provides an ~orderless~ completion style.

#+begin_src emacs-lisp
  (use-package orderless
    :custom
    (completion-styles '(orderless basic))
    (completion-category-overrides '((file (styles basic partial-completion)))))
#+end_src

* Editing

[[https://github.com/magnars/multiple-cursors.el][multiple-cursors]] provides /multiple cursors/..

#+begin_src emacs-lisp
  (use-package multiple-cursors
    :bind (
           ("C->" . mc/mark-next-like-this)
           ("C-<" . mc/mark-previous-like-this)))
#+end_src

* Dealing with Delimiters

[[https://github.com/Fuco1/smartparens][smartparens]] deals with delimiters in a smart way.

#+begin_src emacs-lisp
  (use-package smartparens
    :hook
    (prog-mode . smartparens-mode)
    :config
    (require 'smartparens-config))
#+end_src

[[https://github.com/Fanael/rainbow-delimiters][rainbow-delimiters]] highlights delimiters (e.g.: ~()~, ~{}~, ~[]~).

#+begin_src emacs-lisp
  (use-package rainbow-delimiters
    :hook
    (prog-mode . rainbow-delimiters-mode))
#+end_src

* Version Control

[[https://magit.vc/][magit]] is a text based UI to [[https://git-scm.com/][git]].

#+begin_src emacs-lisp
  (use-package magit)
#+end_src

[[https://github.com/emacsmirror/git-timemachine][git-timemachine]] allows you to go back and forth through time.

#+begin_src emacs-lisp
  (use-package git-timemachine)
#+end_src

* Org Mode

For compatibily reasons, i keep the org bundled with the emacs build.

#+begin_src emacs-lisp
  (use-package org
    :straight nil
    :custom
    (org-startup-indented t)
    (org-hide-emphasis-markers t)
    (org-special-ctrl-a/e t)
    (org-log-done 'time)
    :bind (
           ("C-c a" . org-agenda)
           ("C-c l" . org-store-link)
           :map org-mode-map
           ([remap imenu] . consult-org-heading)))
#+end_src

* Programming

** tree-sitter

Since version 29, emacs can be built with support for tree-sitter. Basically, tree-sitter enhances understanding of source code.

#+begin_src emacs-lisp
  (require 'treesit)
#+end_src

Tree-sitter itself doesn't know how to parse any language, for that, we need to install language grammars libraries.

Emacs will look for these libraries in directories listed in the ~treesit-extra-load-path~ variable, then in the the tree-sitter subdir in ~user-emacs-directory~ (e.g.: ~/.config/emacs/tree-sitter/~), and then in the standard system directories for shared libraries.

You install these libraries using the ~treesit-install-language-grammar~ command. The ~treesit-language-source-alist~ variable can tell the command where to look for the libraries.

#+begin_src emacs-lisp
  (setq treesit-language-source-alist
        '((c "https://github.com/tree-sitter/tree-sitter-c")
          (python "https://github.com/tree-sitter/tree-sitter-python")))
#+end_src

The following elisp installs grammar libraries that aren't already installed.

#+begin_src emacs-lisp
  (dolist (lang treesit-language-source-alist)
    (unless (treesit-language-available-p (car lang))
      (treesit-install-language-grammar (car lang))))
#+end_src

The langugage specified may be named differently than its library. You can use the ~treesit-load-name-override-list~ variable to map the language to the correct library name.

The default way emacs implements syntax-highlighting is very different than the way tree-sitter does. Emacs does it with a lot of regex, tree-sitter parses the code into a syntax tree.

Because of that, instead of embed tree-sitter in existing programming modes, there are new "ts"-powered modes.

You can customize the ~major-mode-remap-alist~ to automatically turn on tree-sitter based modes.

#+begin_src emacs-lisp
  (setq major-mode-remap-alist
        '((c-mode . c-ts-mode)
          (python-mode . python-ts-mode)))
#+end_src

** eglot

[[https://joaotavora.github.io/eglot/][eglot]] is a LSP client built into emacs since version 29.1.

For eglot to be useful you must combine it with a language server. The language server must be installed separately.

The variable ~eglot-server-programs~ associates major modes with names and arguments of the language server for that programming language.

You can run ~eglot~ in a buffer to start the language server for that major mode. You can also set eglot to start automatically with hooks:

#+begin_src emacs-lisp
  (use-package eglot
    :straight nil
    :config
    (add-to-list 'eglot-server-programs
                 '(c-ts-mode . ("clangd"))
                 '(python-ts-mode . ("pyright")))
    :hook
    (c-ts-mode . eglot-ensure)
    (python-ts-mode . eglot-ensure))
#+end_src

** ELDoc box

[[https://github.com/casouri/eldoc-box][ELDoc box]] displays eldoc documentation in a box.

#+begin_src emacs-lisp
  (use-package eldoc-box
    :hook
    (eldoc-mode . eldoc-box-hover-at-point-mode))
#+end_src

** expreg

[[https://github.com/casouri/expreg][expreg]] is a [[https://github.com/magnars/expand-region.el][expand-region]] but with some advantages, including the use of tree-sitter.

#+begin_src emacs-lisp
  (use-package expreg
    :bind (
           ("C-=" . expreg-expand)
           ("C-+" . expreg-contract)))
#+end_src

* PDF Tools

[[https://github.com/vedang/pdf-tools?tab=readme-ov-file][PDF Tools]] is a replacement for DocView for PDF files. PDF tools requires a server ~epdfinfo~.

#+begin_src emacs-lisp
  (use-package pdf-tools)
#+end_src

You can install the ~epdfinfo~ program by running the command ~pdf-tools-install~.

[[https://github.com/007kevin/pdf-view-restore][pdf-view-restore]] provides support for opening PDF documents in last known position.

#+begin_src emacs-lisp
  (use-package pdf-view-restore
    :after pdf-tools
    :custom
    (pdf-view-restore-filename "~/.config/emacs/.pdf-view-restore")
    :hook
    (pdf-view-mode . pdf-view-restore-mode))
#+end_src
